travis:
  secure:
    BINSTAR_TOKEN: JKZ8KsuhFGDVC24Io5hPdT+b+ArvdQEUsN+9nf/cxQsVt9R56RTeCHMiwUv0YPcvX/FPL84QRILJVQEe64Rp/SsrPIt9vUbsRPGli7F/veQ0ghO+SG2rz0uKzMjM4DOxYuu8ads2Wn9Nh7sPk1DE1eq6tTBhorARcoQC5gMI7d8b1vM1qVeUxJys5D5rzQmSXsr1pRnF0YnaWZg3wyKGbx0zyKMYWeiZ0EFHU9IZYJHof6moZVYnRVZsu6FIFiRMSkNQV+gHm4RPodxWiWjj97d2uir4C1aAfsgfCI4AzPRc41hq5qSY9V1KKAwg05yOqigv1s5Fmhn8XDDIltecsfNQZW0rfwC4mupli3lbJ4P+AokqrPm/+u2JlwDLJVoA3ju0RLR0VLwzF0GRokly3qRMhBvXiXuZ/MIeI5vQF4CP3K+Te06L2+rZWFhP5uUVgeF6LT0JIU7RrreZvtcZMXBz4N/wsQ0TKWIq78EcodGbVdcUBX9eVexcgwPSqvGIszV8b+OqaEZ8JotkeXLkatIMtz4BpZoYoL4IBE2aWs4RaSD9IoDfjow+M7ylU+yvQhG6VoJo2FVxNUYWMbdU1Xg/275wOJfdgkja9JOzeTW0O96kPHXCBjdf1hJN/ArXn9ys2ohvcY7CZla7tpAynyCKV+22MtA7O/x8+ujX8e8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
