travis:
  secure:
    BINSTAR_TOKEN: N6TKjjobkNv9SYcnFw1TPGLdAjfXK0Er7UnrLREZ3pihUyVK/PNyDAxchWQbiinFqtyoIeomFj5rOP5V8rdF05p0Oro8MKrqVnNYu9I1WIYuWj8p1q9ZtFFnYczn0UQtN/tB8c45C5MzToD0PzL8fmNmqKrkEBYtMRlS9vmCBVAlxehdcAyJX9+7MmvyAoDnN60gd628XsCNZ00r0wsMZO5QXiETbzMKC8/WlwnGS0MKMgaCziZrXO0aA007wlMs3dAcWFqbUbH8PaHhGh0tUgMDE3WD+zPs6E7p2+20aGYhr/fkIcmRKwkdJrrRTA2Yb6D7xnYUgrWkHFvvP9KN/0xgdFiG8FtdaeLqUtAL6qDGVzbVesFmLdLHvc9jDq90WnFgOSgimaAtXdVH3bsZapYE0tu/5kvVpdqh2SsskVxNyvCoHxZzsYovLP7OWVqx7Wmj5QnH2bLKB2yX7F0grRohZDPkSW4d+uX0uZEU6HgjM6SS+yFLsoV5cfCycrv1INBzuzla+32hlfh4+6ccD7q9C9PSGhi9+Z/DKztfG6P3lejeKXrsDkJq6mV9s6owlyxqouToyP1r0dQ8Ls7+eKnYDfqslv3Uo3QigsYo9vqTnGQvjrWRng5jSLmuqdjIRJlaUUdp8B9wFgtjf/zGww7rlpHYyHfS1KVQZUDcxk4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
