travis:
  secure:
    BINSTAR_TOKEN: fTcrLLtCKIwowq5IEOeaYmRyOSbIUHdlAeH5VXejyiY5Vx3YQ9dqxRj6oTmXz/8je3+fyH/2soqe95oiocvXTTDFRDv6IFJgabd018N4THOpqGbs0I3BP1lpVBMlqOdWboYIwAtDS1w6G17AO0ozYdlvvyvd6hc/I0eupuHuvZmJY7gHPeHAeS02yikeQGCdvTtUDOdA3/hh/uF9YBne64iE+53NxYPnLUYNuvDLhFLSr1iokkPkJ+RO6Eq9WJP0spx5L5hoXIHwn2nLfjGagR8yRdjDyjoNipvE319we3GyVjPJlHkDxH10dcIxVdlj6bdvGIqaBDcC3W++BP6frJkTMoBDobVP9UcBo5dASL+3nKp2W0LNNhqZwqANZMFWEUhACsEYmgDf8c68ggg/AdY4mVNUtzuB8NvFuxKJcRRYIm7ndG7MmmapcYrlxqXRIoC8rgxXuH4n2NwOpBbZmIKtSnDoXhIGqFAgDHVnf2EzgKdn/yJ350eKGpc/pAEuhNr+dZp7dklk6Cw+m9FHWCokpoavXGdiYPbXhW+l1W6NVqYo44DT9boY13pB9A+LDxISIP0i6Zx70uiuCNCY3aLmeGv1+YjksFnSV24oPw/hGCpYFbTOzKt6luYgV3OHVFzLDN19bNfnwxciaiTWUtDRuZmXD/qmIVSrnS7fXD0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
